---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fedora
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - jdxcode/mise
    install:
      packages:
        - micro
        - starship
        - fish
        - android-tools
        - distrobox
        - mise
        - bat
        - lsd
        - age
        - podman-compose
        - podman-docker
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - gnome-software
        - gnome-software-rpm-ostree
        - PackageKit-glib
  
  - type: script
    scripts:
      - set-shell.sh
  
  - type: fonts
    fonts:
      nerd-fonts:
        - AdwaitaMono
  
  - type: gschema-overrides
    include:
      - zz1-myoverride.gschema.override

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox # Firefox (Browser)
          - org.gnome.Loupe # Loupe (Image Viewer)
          - com.github.neithern.g4music # Gapless (Music Player)
          - io.github.flattool.Warehouse # Warehouse
          - org.gnome.DejaDup # DejaDub (Backup)
          - org.gnome.FileRoller # File Roller
          - com.github.tchx84.Flatseal # Flatseal
          - io.mpv.Mpv # MPV (Media Player)
          - org.gnome.NautilusPreviewer
          - org.gnome.Papers # Papers (Pdf Viewer)
      - scope: user # Also add Flathub user repo, but no user packages
        install:
          - dev.vencord.Vesktop # Vesktop (Discord)
          - org.cryptomator.Cryptomator # Cryptomator
          - org.signal.Signal # Signal
          - com.visualstudio.code # Visual Studio Code
          - md.obsidian.Obsidian # Obsidian
          - com.ranfdev.DistroShelf # DistroShelf (Distrobox)

  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
      - 4478
      - 8852
  
  - type: bling
    install:
      - dconf-update-service

  - type: chezmoi
    disable-init: false
    repository: 'https://github.com/cause-dev/dotfiles'
    branch: "main"
    file-conflict-policy: "replace"
    disable-update: true
  
  - type: systemd
    system:
      disabled:
        - system-flatpak-setup.timer
        - flatpak-system-update.timer
        - rpm-ostreed-automatic.timer
    
    user:
      disabled:
        - user-flatpak-setup.timer
        - flatpak-user-update.timer
      enabled:
        - podman.socket

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
