- type: script
  scripts:
    - set-shell.sh

- type: fonts
  fonts:
    nerd-fonts:
      - AdwaitaMono

- type: gschema-overrides
  include:
    - zz1-myoverride.gschema.override

- from-file: includes/flatpaks.yml

- type: gnome-extensions
  install:
    - AppIndicator and KStatusNotifierItem Support
    - 4478
    - 8852

- type: bling
  install:
    - dconf-update-service
